### ISSUE TITLE
CC0045, StringRepresentationAnalyzer

### ISSUE THREAD

**Issue by casterle** [code-cracker/code-cracker.github.io#19]
In this line of code:

`selectCommand.Parameters.AddWithValue("@pkid", id);`

I am getting a suggestion to "Convert `"@pkid"` to verbatim string". I don't understand the benefit of doing so. If the string were, say, `"c:\\stuff"` I see the benefit, but not in this case. 

Is there a good reason I am receiving this suggestion?

**Comment by giggio** [comment]
I am moving this to a new issue on the correct repo. See https://github.com/code-cracker/code-cracker/issues/736.
